# Generated by Django 5.1.3 on 2025-01-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentproperty_details', models.CharField(max_length=50)),
                ('rentproperty_price', models.CharField(max_length=50)),
                ('rentproperty_photo', models.FileField(upload_to='Assets/user/photo')),
                ('rentproperty_category', models.CharField(max_length=50)),
            ],
        ),
    ]
