# Generated by Django 5.1.3 on 2025-01-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentproperty',
        ),
    ]
