# Generated by Django 5.1.3 on 2025-01-30 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0005_tbl_place'),
        ('Owner', '0002_delete_tbl_rentproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentproperty_details', models.CharField(max_length=50)),
                ('rentproperty_price', models.CharField(max_length=50)),
                ('rentproperty_photo', models.FileField(upload_to='Assets/owner/photo')),
                ('rentproperty_category', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
