# Generated by Django 5.1.3 on 2025-01-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentproperty',
        ),
    ]
