# Generated by Django 5.1.3 on 2025-02-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0006_tbl_sellproperty'),
        ('User', '0004_alter_tbl_rentbooking_rentbooking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sellproperty',
        ),
    ]
