# Generated by Django 5.1.3 on 2025-02-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0008_tbl_sellproperty'),
        ('User', '0006_delete_tbl_rentbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentproperty',
        ),
    ]
