# Generated by Django 5.1.3 on 2025-02-27 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place'),
        ('Owner', '0009_delete_tbl_rentproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rentproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentproperty_location', models.CharField(max_length=50)),
                ('rentproperty_type', models.CharField(max_length=50)),
                ('rentproperty_rentaltype', models.CharField(max_length=50)),
                ('rentproperty_price', models.CharField(max_length=50)),
                ('rentproperty_photo', models.FileField(upload_to='Assets/owner/photo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
