# Generated by Django 5.1.3 on 2025-03-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0010_tbl_rentproperty'),
        ('User', '0012_delete_tbl_rentbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentproperty',
        ),
    ]
