# Generated by Django 5.1.3 on 2025-03-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0012_tbl_rentproperty'),
        ('User', '0014_delete_tbl_bookproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sellproperty',
        ),
    ]
