# Generated by Django 5.1.3 on 2025-01-23 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_place'),
        ('Guest', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_email', models.CharField(max_length=50)),
                ('owner_contact', models.CharField(max_length=50)),
                ('owner_address', models.CharField(max_length=50)),
                ('owner_photo', models.FileField(upload_to='Assets/user/photo')),
                ('owner_password', models.CharField(max_length=50)),
                ('owner_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
