# Generated by Django 5.1.3 on 2025-02-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0005_tbl_owner_owner_status'),
        ('Owner', '0006_tbl_sellproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bookproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookproperty_date', models.DateField(auto_now_add=True)),
                ('bookproperty_amount', models.CharField(max_length=50)),
                ('bookproperty_status', models.IntegerField(default=0)),
                ('bookproperty_sellproperty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_sellproperty')),
                ('bookproperty_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
