# Generated by Django 5.1.3 on 2025-02-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_bookproperty_user_id_tbl_bookproperty_bookpropertyuser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_rentbooking',
            name='rentbooking_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='tbl_bookproperty',
        ),
    ]
