# Generated by Django 5.1.3 on 2025-02-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_bookproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentbooking',
        ),
    ]
