# Generated by Django 5.1.3 on 2025-02-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_rentbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentbooking',
        ),
    ]
