# Generated by Django 5.1.3 on 2025-03-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_tbl_rentbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rentbooking',
        ),
    ]
