# Generated by Django 5.1.3 on 2025-03-07 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0013_tbl_rentbooking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_bookproperty',
        ),
    ]
