# Generated by Django 5.1.3 on 2025-03-07 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_owner_owner_status'),
        ('Owner', '0014_tbl_sellproperty'),
        ('User', '0014_delete_tbl_bookproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bookproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookproperty_date', models.DateField(auto_now_add=True)),
                ('bookproperty_amount', models.CharField(max_length=50)),
                ('bookproperty_status', models.IntegerField(default=0)),
                ('bookproperty_sellproperty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Owner.tbl_sellproperty')),
                ('bookpropertyuser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
