# Generated by Django 5.1.3 on 2025-03-07 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_bookproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
