# Generated by Django 5.1.3 on 2025-03-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_tbl_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_rentbooking',
            old_name='rentproperty_status',
            new_name='rentbooking_status',
        ),
    ]
