# Generated by Django 5.1.3 on 2025-03-07 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_owner_owner_status'),
        ('User', '0018_rename_rentproperty_status_tbl_rentbooking_rentbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('owner_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_from', to='Guest.tbl_owner')),
                ('owner_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_to', to='Guest.tbl_owner')),
                ('user_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_from', to='Guest.tbl_user')),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_to', to='Guest.tbl_user')),
            ],
        ),
    ]
